"""Shareable influencer shortlist report, ranked by segment.

Reads all creators from Supabase, ranks them by composite_score within each
segment, and builds a clean plain-text report: top 10 crypto-curious, top 5
remittance, top 3 iGaming — each with name, subscribers, composite score,
deposit-relevance score, and a one-line pitch angle generated by Claude
(claude-sonnet-4-6) from the creator's niche_tags and segment. A single Claude
call covers all listed creators. Saves to docs/influencer_report_<date>.txt and
prints to terminal.

Run from repo root:  python intelligence/influencer_report.py
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from anthropic import Anthropic
from dotenv import load_dotenv

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

load_dotenv()

from creators import database

_DOCS_DIR = _ROOT / "docs"
_MODEL = "claude-sonnet-4-6"

# (segment_tag, how many to show), in report order.
_SEGMENT_PLAN = [
    ("crypto-curious", 10),
    ("remittance", 5),
    ("iGaming", 3),
]
_SEGMENT_TITLES = {
    "crypto-curious": "TOP 10 CRYPTO-CURIOUS",
    "remittance": "TOP 5 REMITTANCE",
    "iGaming": "TOP 3 iGAMING",
}


# ------------------------------------------------------------------
# Selection
# ------------------------------------------------------------------

def select_by_segment(rows: list[dict]) -> dict[str, list[dict]]:
    """Top-N creators per segment by composite_score (descending)."""
    selected: dict[str, list[dict]] = {}
    for seg, n in _SEGMENT_PLAN:
        in_seg = [r for r in rows if r.get("segment_tag") == seg]
        in_seg.sort(key=lambda r: r.get("composite_score", 0), reverse=True)
        selected[seg] = in_seg[:n]
    return selected


# ------------------------------------------------------------------
# Claude pitch angles (one call for all listed creators)
# ------------------------------------------------------------------

def generate_pitch_angles(selected: dict[str, list[dict]]) -> dict[str, str]:
    """Return {creator_name: one-line pitch angle} from a single Claude call.

    Falls back to an empty dict (callers render a neutral placeholder) if the
    API key is missing or the response can't be parsed.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return {}

    creators = []
    for seg, items in selected.items():
        for r in items:
            creators.append({
                "name": r.get("name", ""),
                "segment": seg,
                "niche_tags": r.get("niche_tags") or [],
            })
    if not creators:
        return {}

    prompt = (
        "You are a partnerships strategist for Speed Wallet, a Bitcoin Lightning "
        "payments app. Segment hooks: remittance -> zero fees on cross-border "
        "sends; iGaming -> instant deposits/withdrawals; crypto-curious -> "
        "simplicity and real-world utility.\n\n"
        "For EACH creator below, write ONE punchy pitch angle (max ~15 words) — "
        "how Speed should approach them, grounded in their niche_tags and "
        "segment. No fluff, no generic crypto talk.\n\n"
        'Return ONLY a JSON array of objects: {"name": "<exact name>", '
        '"angle": "<one line>"}. No other text.\n\n'
        f"CREATORS:\n{json.dumps(creators, ensure_ascii=False, indent=2)}"
    )

    try:
        client = Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=_MODEL,
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}],
        )
        return _parse_angles(resp.content[0].text)
    except Exception as e:  # noqa: BLE001 — report degrades to placeholders
        print(f"  (pitch-angle generation failed: {type(e).__name__}: {e})")
        return {}


def _parse_angles(text: str) -> dict[str, str]:
    text = text.strip()
    try:
        val = json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\[.*\]", text, re.DOTALL)
        if not m:
            return {}
        try:
            val = json.loads(m.group())
        except json.JSONDecodeError:
            return {}
    angles: dict[str, str] = {}
    if isinstance(val, list):
        for item in val:
            if isinstance(item, dict) and item.get("name"):
                angles[str(item["name"]).strip()] = str(item.get("angle", "")).strip()
    return angles


# ------------------------------------------------------------------
# Report
# ------------------------------------------------------------------

def build_report(selected: dict[str, list[dict]], angles: dict[str, str],
                 total: int, generated_at: str) -> str:
    lines = [
        "=" * 70,
        "SPEED WALLET — INFLUENCER SHORTLIST",
        f"Generated {generated_at} · {total} creators in database",
        "Ranked by composite partnership score within each segment.",
        "=" * 70,
    ]

    for seg, _n in _SEGMENT_PLAN:
        items = selected.get(seg, [])
        lines.append("")
        lines.append(_SEGMENT_TITLES[seg] + f"  ({len(items)})")
        lines.append("-" * 70)
        if not items:
            lines.append("  (no creators tagged in this segment yet)")
            continue
        for i, r in enumerate(items, 1):
            name = r.get("name", "Unknown")
            subs = int(r.get("followers", 0))
            score = r.get("composite_score", 0)
            drs = r.get("deposit_relevance_score", 0)
            angle = angles.get(name, "").strip() or "(pitch angle unavailable)"
            lines.append(
                f"{i:>2}. {name} — {subs:,} subs · score {score}/100 · "
                f"deposit relevance {drs}/20"
            )
            lines.append(f"     Pitch: {angle}")
    lines.append("")
    lines.append("=" * 70)
    return "\n".join(lines)


# ------------------------------------------------------------------
# Save + entrypoint
# ------------------------------------------------------------------

def save_report(text: str) -> Path:
    _DOCS_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y_%m_%d")
    path = _DOCS_DIR / f"influencer_report_{today}.txt"
    path.write_text(text + "\n", encoding="utf-8")
    return path


def run() -> str:
    print("Reading all creators from Supabase...")
    rows = database.get_all_creators()
    print(f"  {len(rows)} creators total")

    selected = select_by_segment(rows)
    counts = ", ".join(f"{seg}={len(items)}" for seg, items in selected.items())
    print(f"  Selected: {counts}")

    print(f"Generating pitch angles ({_MODEL})...")
    angles = generate_pitch_angles(selected)
    print(f"  {len(angles)} pitch angles generated")

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    report = build_report(selected, angles, len(rows), generated_at)

    path = save_report(report)
    print(f"\nSaved: {path.relative_to(_ROOT)}\n")
    print(report)
    return report


if __name__ == "__main__":
    try:
        run()
    except EnvironmentError as e:
        print(f"Config error: {e}")
        sys.exit(1)
